-- MySQL Script generated by MySQL Workbench
-- Fri Jun 18 15:08:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaGerenciamento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SistemaGerenciamento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaGerenciamento` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `SistemaGerenciamento` ;

-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`Acessorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`Acessorio` (
  `AcessorioId` BIGINT(20) NOT NULL,
  `Tipo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Quantidade` INT(11) NOT NULL,
  PRIMARY KEY (`AcessorioId`),
  UNIQUE INDEX `Tipo` (`Tipo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`AcessorioSala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`AcessorioSala` (
  `AcessorioSalaId` BIGINT(20) NOT NULL,
  `QuantidadeAcessorio` INT(11) NOT NULL,
  `AcessorioId` BIGINT(20) NOT NULL,
  `SalaId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`AcessorioSalaId`),
  UNIQUE INDEX `AcessorioSala_SalaId_AcessorioId_unique` (`AcessorioId` ASC, `SalaId` ASC) VISIBLE,
  INDEX `SalaId` (`SalaId` ASC) VISIBLE,
  CONSTRAINT `AcessorioSala_ibfk_1`
    FOREIGN KEY (`AcessorioId`)
    REFERENCES `SistemaGerenciamento`.`Acessorio` (`AcessorioId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `AcessorioSala_ibfk_2`
    FOREIGN KEY (`SalaId`)
    REFERENCES `SistemaGerenciamento`.`Sala` (`SalaId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`DocumentoRevisao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`DocumentoRevisao` (
  `DocumentoRevisaoId` BIGINT(20) NOT NULL,
  `DescricaoProblema` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `DataAbertura` DATETIME NOT NULL,
  `Status` INT(11) NOT NULL,
  `DataConclusao` DATETIME NULL DEFAULT NULL,
  `Defeito` TINYINT(1) NOT NULL,
  `EquipamentoId` BIGINT(20) NULL DEFAULT NULL,
  `SalaId` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`DocumentoRevisaoId`),
  INDEX `EquipamentoId` (`EquipamentoId` ASC) VISIBLE,
  INDEX `SalaId` (`SalaId` ASC) VISIBLE,
  CONSTRAINT `DocumentoRevisao_ibfk_1`
    FOREIGN KEY (`EquipamentoId`)
    REFERENCES `SistemaGerenciamento`.`Equipamento` (`EquipamentoId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `DocumentoRevisao_ibfk_2`
    FOREIGN KEY (`SalaId`)
    REFERENCES `SistemaGerenciamento`.`Sala` (`SalaId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`Equipamento` (
  `EquipamentoId` BIGINT(20) NOT NULL,
  `Patrimonio` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Status` INT(11) NOT NULL,
  `DataCadastro` DATETIME NOT NULL,
  `TipoEquipamentoId` BIGINT(20) NOT NULL,
  `SalaId` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`EquipamentoId`),
  UNIQUE INDEX `Patrimonio` (`Patrimonio` ASC) VISIBLE,
  INDEX `TipoEquipamentoId` (`TipoEquipamentoId` ASC) VISIBLE,
  INDEX `SalaId` (`SalaId` ASC) VISIBLE,
  CONSTRAINT `Equipamento_ibfk_1`
    FOREIGN KEY (`TipoEquipamentoId`)
    REFERENCES `SistemaGerenciamento`.`TipoEquipamento` (`TipoEquipamentoId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Equipamento_ibfk_2`
    FOREIGN KEY (`SalaId`)
    REFERENCES `SistemaGerenciamento`.`Sala` (`SalaId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`Login` (
  `UsuarioId` BIGINT(20) NULL DEFAULT NULL,
  UNIQUE INDEX `UsuarioId` USING BTREE (`UsuarioId`),
  CONSTRAINT `Login_ibfk_1`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `SistemaGerenciamento`.`Usuario` (`UsuarioId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`Requisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`Requisicao` (
  `RequisicaoId` BIGINT(20) NOT NULL,
  `Tipo` INT(11) NOT NULL,
  `Status` INT(11) NOT NULL,
  `Turno` INT NOT NULL,
  `DataAbertura` DATETIME NOT NULL,
  `DataUtilizacao` DATETIME NULL DEFAULT NULL,
  `DataEntrega` DATETIME NULL DEFAULT NULL,
  `DataConclusao` DATETIME NULL DEFAULT NULL,
  `DataCancelamento` DATETIME NULL DEFAULT NULL,
  `UsuarioId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`RequisicaoId`),
  INDEX `UsuarioId` (`UsuarioId` ASC) VISIBLE,
  CONSTRAINT `Requisicao_ibfk_1`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `SistemaGerenciamento`.`Usuario` (`UsuarioId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`RequisicaoAcessorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`RequisicaoAcessorio` (
  `RequisicaoAcessorioId` BIGINT(20) NOT NULL,
  `QuantidadeAcessorio` INT(11) NOT NULL,
  `RequisicaoId` BIGINT(20) NOT NULL,
  `AcessorioId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`RequisicaoAcessorioId`),
  UNIQUE INDEX `RequisicaoAcessorio_RequisicaoId_AcessorioId_unique` (`RequisicaoId` ASC, `AcessorioId` ASC) VISIBLE,
  INDEX `AcessorioId` (`AcessorioId` ASC) VISIBLE,
  CONSTRAINT `RequisicaoAcessorio_ibfk_1`
    FOREIGN KEY (`RequisicaoId`)
    REFERENCES `SistemaGerenciamento`.`Requisicao` (`RequisicaoId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `RequisicaoAcessorio_ibfk_2`
    FOREIGN KEY (`AcessorioId`)
    REFERENCES `SistemaGerenciamento`.`Acessorio` (`AcessorioId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`RequisicaoEquipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`RequisicaoEquipamento` (
  `RequisicaoEquipamentoId` BIGINT(20) NOT NULL,
  `RequisicaoId` BIGINT(20) NOT NULL,
  `EquipamentoId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`RequisicaoEquipamentoId`),
  UNIQUE INDEX `RequisicaoEquipamento_RequisicaoId_EquipamentoId_unique` (`RequisicaoId` ASC, `EquipamentoId` ASC) VISIBLE,
  INDEX `EquipamentoId` (`EquipamentoId` ASC) VISIBLE,
  CONSTRAINT `RequisicaoEquipamento_ibfk_1`
    FOREIGN KEY (`RequisicaoId`)
    REFERENCES `SistemaGerenciamento`.`Requisicao` (`RequisicaoId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `RequisicaoEquipamento_ibfk_2`
    FOREIGN KEY (`EquipamentoId`)
    REFERENCES `SistemaGerenciamento`.`Equipamento` (`EquipamentoId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`RequisicaoSala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`RequisicaoSala` (
  `RequisicaoSalaId` BIGINT(20) NOT NULL,
  `RequisicaoId` BIGINT(20) NOT NULL,
  `SalaId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`RequisicaoSalaId`),
  UNIQUE INDEX `RequisicaoSala_SalaId_RequisicaoId_unique` (`RequisicaoId` ASC, `SalaId` ASC) VISIBLE,
  INDEX `SalaId` (`SalaId` ASC) VISIBLE,
  CONSTRAINT `RequisicaoSala_ibfk_1`
    FOREIGN KEY (`RequisicaoId`)
    REFERENCES `SistemaGerenciamento`.`Requisicao` (`RequisicaoId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `RequisicaoSala_ibfk_2`
    FOREIGN KEY (`SalaId`)
    REFERENCES `SistemaGerenciamento`.`Sala` (`SalaId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`RequisicaoTipoEquipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`RequisicaoTipoEquipamento` (
  `RequisicaoTipoEquipamentoId` BIGINT(20) NOT NULL,
  `QuantidadeSolicitada` INT(11) NOT NULL,
  `RequisicaoId` BIGINT(20) NOT NULL,
  `TipoEquipamentoId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`RequisicaoTipoEquipamentoId`),
  UNIQUE INDEX `RequisicaoTipoEquipamento_TipoEquipamentoId_RequisicaoId_unique` (`RequisicaoId` ASC, `TipoEquipamentoId` ASC) VISIBLE,
  INDEX `TipoEquipamentoId` (`TipoEquipamentoId` ASC) VISIBLE,
  CONSTRAINT `RequisicaoTipoEquipamento_ibfk_1`
    FOREIGN KEY (`RequisicaoId`)
    REFERENCES `SistemaGerenciamento`.`Requisicao` (`RequisicaoId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `RequisicaoTipoEquipamento_ibfk_2`
    FOREIGN KEY (`TipoEquipamentoId`)
    REFERENCES `SistemaGerenciamento`.`TipoEquipamento` (`TipoEquipamentoId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`Sala` (
  `SalaId` BIGINT(20) NOT NULL,
  `NumeroSala` INT(11) NOT NULL,
  `Status` INT(11) NOT NULL,
  `QuantidadeAluno` INT(11) NOT NULL,
  `QuantidadeAlunoPandemia` INT(11) NOT NULL,
  PRIMARY KEY (`SalaId`),
  UNIQUE INDEX `NumeroSala` (`NumeroSala` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`TipoEquipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`TipoEquipamento` (
  `TipoEquipamentoId` BIGINT(20) NOT NULL,
  `NomeTipo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`TipoEquipamentoId`),
  UNIQUE INDEX `NomeTipo` (`NomeTipo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SistemaGerenciamento`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGerenciamento`.`Usuario` (
  `UsuarioId` BIGINT(20) NOT NULL,
  `Nome` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Login` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Senha` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Identificacao` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Tipo` INT(11) NOT NULL,
  `Email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`UsuarioId`),
  UNIQUE INDEX `Usuario` (`Login` ASC) VISIBLE,
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Identificacao` (`Identificacao` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
